"""inboxes and messages

Revision ID: ddd5b1e7dce8
Revises: 5c4e8b90be0c
Create Date: 2026-08-27 15:58:42.881445
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ddd5b1e7dce8"
down_revision: str | None = "5c4e8b90be0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inboxes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("address", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inboxes_address"), "inboxes", ["address"], unique=True)
    op.create_index("ix_inboxes_expires_at", "inboxes", ["expires_at"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inbox_id", sa.Uuid(), nullable=False),
        sa.Column("sender", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=998), nullable=False),
        sa.Column("text_body", sa.Text(), nullable=False),
        sa.Column("html_body", sa.Text(), nullable=True),
        sa.Column("otp", sa.String(length=16), nullable=True),
        sa.Column("verification_link", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["inbox_id"], ["inboxes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_messages_expires_at", "messages", ["expires_at"], unique=False)
    op.create_index(
        "ix_messages_inbox_received", "messages", ["inbox_id", "received_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_inbox_received", table_name="messages")
    op.drop_index("ix_messages_expires_at", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_inboxes_expires_at", table_name="inboxes")
    op.drop_index(op.f("ix_inboxes_address"), table_name="inboxes")
    op.drop_table("inboxes")
    # ### end Alembic commands ###
